[Paths]
# Пути к папкам. Если оставить пустыми, бот применит дефолтные значения.
# Аргументы командной строки при запуске будут иметь более высокий приоритет.
# log_dir = /var/log/pptx2png
# shm_dir = /dev/shm/my_custom_tasks

[Limits]
# Пример будущих параметров, которые вы сможете здесь хранить:
# max_file_size_mb = 50
# process_timeout_sec = 300

[YandexDisk]
# Базовая папка на Яндекс.Диске
base_path = /01_СЛАЙДЫ (nbc.church)/Готовые презентации для проектора и трансляции

# Имена подпапок внутри папки даты
source_folder = Служение
target_folder = Трансляция

# Подпапка внутри Трансляции, куда бот складывает свои PNG
pptx2png_folder = pptx2png

# Подпапка для проповеди (внутри pptx2png_folder)
sermon_folder = проповедь - png

# Ключевое слово для поиска в заметках
sermon_keyword = проповед

# Файл со структурой папок
template_file = template.yaml
