[Paths]
# Пути к папкам. Если оставить пустыми, бот применит дефолтные значения.
# Аргументы командной строки при запуске будут иметь более высокий приоритет.
# log_dir = /var/log/pptx2png
# shm_dir = /dev/shm/my_custom_tasks

[Limits]
# Пример будущих параметров, которые вы сможете здесь хранить:
# max_file_size_mb = 50
# process_timeout_sec = 300
